### PR TITLE
[PLATFORM-1243]: Fix interaction with multiclient auth0_ex

### PR DESCRIPTION
**Pull request by cpiemontese**
https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/PLATFORM-1243

Fuuuuu

### CODE REVIEW

**Review by cottinisimone — APPROVED** [review]
lol

**Review by cottinisimone — APPROVED** [review]
Can we maybe retire 0.6.0 and 0.6.1 version in hex.pm? (i remember there's the chance to set it as `usage of this is discouraged`)

**Comment by mustela** [comment]
Hey there! Not sure why did you remove the default array values because I can't access to that ticket, but in this latest version we are now having 

```
** (Mix) Could not start application prima_auth0_ex: exited in: PrimaAuth0Ex.Application.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (ArgumentError) argument error
            :erlang.++(nil, [])
            (prima_auth0_ex 0.6.2) lib/prima_auth0_ex/application.ex:19: PrimaAuth0Ex.Application.start/2
            (kernel 8.5.1) application_master.erl:293: :application_master.start_it_old/4
```

It's basically trying to join an array with a nil value now.

**Comment by mustela** [comment]
Oh wait, I saw the way you set the configs are now different. Sorry didn't see that in this PR. All good now!

**Pull request merged**
